name: AutoPack
on:
    push:
        tags:
        - "V*"
jobs:
    AutoPack:
        name: AutoPack
        runs-on: ubuntu-latest

        steps:
            - name: PackConfigs
              run: |
                mkdir ApodidaeWorkFlows
                cd ApodidaeWorkFlows
                git clone -b Configs https://github.com/naranyinyun/Apodidae.git ApodidaeConfigs
                cd ApodidaeConfigs
                tar -cvf Configs.Apodidae.tar --exclude=.git --exclude=Configs.tar  --exclude=.github *
                cd ..
                git clone -b Magisk https://github.com/naranyinyun/Apodidae.git ApodidaeModule
                cp ApodidaeConfigs/{dimensity1000,dimensity1100,dimensity700,dimensity8100,dimensity820,dimensity900,dimensity9000,helio_g80,helio_g90}.json ApodidaeModule/configs
                cp ApodidaeConfigs/LICENSE ApodidaeModule/configs
                cd ApodidaeModule
                zip -r Magisk.Apodidae.zip * -x=".git"
                cd ..
            - name: CreateRelease
              uses: ncipollo/release-action@v1
              with:
                artifacts: | 
                  "~/ApodidaeWorkFlows/ApodidaeModule/Magisk.Apodidae.zip"
                  "~/ApodidaeWorkFlows/ApodidaeConfigs/Configs.Apodidae.tar"
                draft: true
                allowUpdates: true
                token: ${{secrets.PERSONAL_RTOKEN}}
              

