name: AutoPack
on: 
    push:
        tags: "V*"

jobs:
    AutoPack:
        name: AutoPack
        runs-on: ubuntu-latest

        steps:
            - name: PackConfigs
              run: |
                mkdir ApodidaeWorkFlows
                cd ApodidaeWorkFlows
                git clone -b Configs https://github.com/naranyinyun/Apodidae.git ApodidaeConfigs
                cd ApodidaeConfigs
                tar -cvf ConfigsApodidae.tar --exclude=.git --exclude=Configs.tar  --exclude=.github *
                cd ..
                git clone -b Magisk https://github.com/naranyinyun/Apodidae.git ApodidaeModule
                cp ApodidaeConfigs/{dimensity1000,dimensity1100,dimensity700,dimensity8100,dimensity820,dimensity900,dimensity9000,helio_g80,helio_g90,tegra_x1}.json ApodidaeModule/configs
                cp ApodidaeConfigs/LICENSE ApodidaeModule/configs
                cd ApodidaeModule
                zip -r MagiskApodidae.zip * -x=".git"
                cd ..
                mv /home/runner/work/Apodidae/Apodidae/ApodidaeWorkFlows/ApodidaeModule/MagiskApodidae.zip /home/runner/work/Apodidae
                mv /home/runner/work/Apodidae/Apodidae/ApodidaeWorkFlows/ApodidaeConfigs/ConfigsApodidae.tar /home/runner/work/Apodidae
                mv /home/runner/work/Apodidae/Apodidae/ApodidaeWorkFlows/ApodidaeConfigs/changelog.md /home/runner/work/Apodidae
                cd /home/runner/work/Apodidae
            - name: CreateRelease
              uses: softprops/action-gh-release@v0.1.15
              with: 
                draft: true
                token: ${{secrets.PERSONAL_RTOKEN}}
                files: |
                  /home/runner/work/Apodidae/MagiskApodidae.zip
                  /home/runner/work/Apodidae/ConfigsApodidae.tar
                body_path: /home/runner/work/Apodidae/changelog.md
            - name: UploadMirror
              uses: Horze-International/action-upload-webdav@v1
              with: 
                webdav_address: ${{secrets.WEBDAV_URL}}
                webdav_username: ${{secrets.WEDAV_USERNAME}}
                webdav_password: ${{secrets.WEDAV_PASSWORD}}
                webdav_upload_path: /home
                files: |
                  /home/runner/work/Apodidae/MagiskApodidae.zip
                  /home/runner/work/Apodidae/ConfigsApodidae.tar

                  
            
